### ISSUE TITLE
Wrong AMI in template-two (part-two)?

### ISSUE THREAD

**Issue by flosell** [kgxsz/devops-101#3]
Running CloudFormation like described in part-two gives me this error: 
`AWS::EC2::Instance   EC2Instance API: ec2:RunInstances Not authorized for images: [ami-25865252]`

Changing the `ImageId` to `ami-20bd1f57` fixed this for me.

**Comment by ella-jennings** [comment]
I'm also getting this error:  
`CREATE_FAILED | AWS::EC2::Instance | EC2Instance | API: ec2:RunInstances Not authorized for images: [ami-20bd1f57]`

My region is definitely eu-west-1. I am unable to find this ami when I search in public images within the AWS AMI's menu. I realise this was last commented on in 2014 - just wondering if it's still available to use?

**Comment by kgxsz** [comment]
Hi @ella-jennings - thanks for flagging this up, and thanks for fixing the issue. If you'd like to submit a pull request with that fix I'd be more than happy to merge it.
